### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by trace-kadenyi** [hammaazarok/icst4#2]
- Commendable design
- Good user interactions for the images on the About page. 
- I particularly appreciate your Sponsor section. It is well-designed and fits on the page perfectly. 

Kindly consider the following issues in your design: 
     - In the Main Program section, some of the content is flowing out of the container. I would suggest that you ensure all your content is contained within its specified container. Setting an appropriate size for the container would be a good way to start. Also, you might consider avoiding setting fixed heights for your containers as this leaves no room for expansion when your content surpasses the size of the container. 
     - Secondly, I would suggest that you improve the design of your Committees section to make it more responsive and appealing. While all the content is placed accordingly, certain screen sizes are not represented well enough. I would suggest using the float property to allow the content to flow around the image. You might also consider increasing the space available to each individual Committee member as what you have provided is too small. 
     -

**Comment by hammaazarok** [comment]
thanks appreciate your feedback it is very helpful
