### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by ishpaul777** [hammaazarok/icst4#3]
You have done an incredible job and project is looking good.
- In the Main Program section, some of the content is flowing out of the container. I would suggest that you ensure all your content is contained within its specified container. Setting an appropriate size for the container would be a good way to start. Also, you might consider avoiding setting fixed heights for your containers as this leaves no room for expansion when your content surpasses the size of the container.

**Comment by hammaazarok** [comment]
thank you for the helpful feedback, the issue was resolved.
